# Generated by Django 3.1.7 on 2021-05-28 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20210528_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Basliq')),
                ('completed', models.BooleanField(blank=True, null=True, verbose_name='Tamamlandi')),
            ],
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
