# Generated by Django 3.1.7 on 2021-06-25 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_auto_20210625_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(upload_to='product_image', verbose_name='Sekil'),
        ),
    ]
