# Generated by Django 3.1.7 on 2021-06-29 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_technology'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('mission', models.CharField(blank=True, max_length=150, null=True)),
                ('image', models.ImageField(upload_to='team_image', verbose_name='Sekil')),
            ],
        ),
    ]
