# Generated by Django 3.1.7 on 2021-07-08 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='team_image', verbose_name='Sekil')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('profession', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
