# Generated by Django 3.2.5 on 2021-07-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='team_image', verbose_name='Sekil')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('profession', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
