# Generated by Django 3.1.7 on 2021-07-08 23:03

from django.db import migrations, models
import django.db.models.deletion
import font_icons.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('font_icons', '0003_auto_20190304_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='about_image', verbose_name='Sekil')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('image', models.ImageField(upload_to='Blog_image', verbose_name='Sekil')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.EmailField(blank=True, max_length=150, null=True)),
                ('subjec', models.CharField(blank=True, max_length=150, null=True)),
                ('message', models.TextField(blank=True, help_text='Send your message', max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('image', models.ImageField(upload_to='News_image', verbose_name='Sekil')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'news',
                'verbose_name_plural': 'news',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('short_description', models.CharField(blank=True, max_length=127, null=True)),
                ('icon', font_icons.models.IconForeignKeyField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='font_icons.fonticonmodel')),
            ],
        ),
        migrations.CreateModel(
            name='Choose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.CharField(blank=True, max_length=127, null=True)),
                ('icon', font_icons.models.IconForeignKeyField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='font_icons.fonticonmodel')),
            ],
        ),
    ]
