# Generated by Django 3.1.7 on 2021-07-01 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_blog_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='icon',
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default=11, upload_to='Category_image', verbose_name='Sekil'),
            preserve_default=False,
        ),
    ]
