# Generated by Django 3.1.7 on 2021-07-08 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210709_0311'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
