# Generated by Django 3.1.7 on 2021-07-08 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_skill_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='eded',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
