# Generated by Django 3.1.7 on 2021-07-08 23:50

from django.db import migrations, models
import django.db.models.deletion
import font_icons.models


class Migration(migrations.Migration):

    dependencies = [
        ('font_icons', '0003_auto_20190304_1154'),
        ('app', '0005_skill_eded'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='permission',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='app.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='skill',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='about_image', verbose_name='Sekil'),
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('icon', font_icons.models.IconForeignKeyField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='font_icons.fonticonmodel')),
            ],
        ),
    ]
