# Generated by Django 3.1.7 on 2021-07-08 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='choose',
            name='short_description1',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='choose',
            name='short_description2',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
    ]
