# Generated by Django 3.1.7 on 2021-07-10 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210710_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(default=11, max_length=150, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
