# Generated by Django 3.1.7 on 2021-07-08 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('font_icons', '0003_auto_20190304_1154'),
        ('app', '0006_auto_20210709_0350'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Permission',
            new_name='Profession',
        ),
    ]
