# Generated by Django 3.1.7 on 2021-07-08 08:44

from django.db import migrations, models
import django.db.models.deletion
import font_icons.models


class Migration(migrations.Migration):

    dependencies = [
        ('font_icons', '0003_auto_20190304_1154'),
        ('app', '0006_auto_20210708_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', font_icons.models.IconForeignKeyField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='font_icons.fonticonmodel')),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='choose',
            old_name='short_description1',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='choose',
            name='short_description2',
        ),
        migrations.RemoveField(
            model_name='choose',
            name='video',
        ),
        migrations.DeleteModel(
            name='Technology',
        ),
    ]
