# Generated by Django 3.1.7 on 2021-07-08 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210709_0355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='permission',
        ),
        migrations.AddField(
            model_name='blog',
            name='profession',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='app.profession'),
            preserve_default=False,
        ),
    ]
