# Generated by Django 3.1.7 on 2021-07-08 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210708_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choose',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='choose',
            name='title',
        ),
        migrations.AlterField(
            model_name='icon',
            name='icon',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='app.choose'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='title',
            name='title',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='app.choose'),
            preserve_default=False,
        ),
    ]
