# Generated by Django 3.1.7 on 2021-07-10 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210710_0609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pese',
            name='icon',
        ),
        migrations.DeleteModel(
            name='News',
        ),
        migrations.DeleteModel(
            name='Pese',
        ),
    ]
