# Generated by Django 3.1.7 on 2021-07-09 00:10

from django.db import migrations, models
import django.db.models.deletion
import font_icons.models


class Migration(migrations.Migration):

    dependencies = [
        ('font_icons', '0003_auto_20190304_1154'),
        ('app', '0008_auto_20210709_0357'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={},
        ),
        migrations.RemoveField(
            model_name='news',
            name='created_at',
        ),
        migrations.AddField(
            model_name='news',
            name='short_description',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(upload_to='Blog_image', verbose_name='Sekil'),
        ),
        migrations.CreateModel(
            name='Pese',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('icon', font_icons.models.IconForeignKeyField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='font_icons.fonticonmodel')),
            ],
        ),
        migrations.AddField(
            model_name='news',
            name='pese',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='app.pese'),
            preserve_default=False,
        ),
    ]
