# Generated by Django 3.1.7 on 2021-07-08 09:14

from django.db import migrations, models
import django.db.models.deletion
import font_icons.models


class Migration(migrations.Migration):

    dependencies = [
        ('font_icons', '0003_auto_20190304_1154'),
        ('app', '0008_auto_20210708_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='title',
        ),
        migrations.AddField(
            model_name='choose',
            name='icon',
            field=font_icons.models.IconForeignKeyField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='font_icons.fonticonmodel'),
        ),
        migrations.AddField(
            model_name='choose',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.DeleteModel(
            name='Icon',
        ),
        migrations.DeleteModel(
            name='Title',
        ),
    ]
