# Generated by Django 3.1.7 on 2021-07-09 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210709_0410'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Projects_Completed', models.CharField(blank=True, max_length=150, null=True)),
                ('Industrires_Served', models.CharField(blank=True, max_length=150, null=True)),
                ('Expert_Team_Mates', models.CharField(blank=True, max_length=150, null=True)),
                ('Happy_Customers', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
