# Generated by Django 3.1.7 on 2021-07-08 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210708_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choose',
            name='short_description',
        ),
    ]
