# Generated by Django 3.1.7 on 2021-07-09 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_counter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Counter',
        ),
    ]
