# Generated by Django 3.1.7 on 2021-07-09 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_delete_counter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Work',
        ),
    ]
