# Generated by Django 3.2.5 on 2021-07-27 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='password1',
            field=models.IntegerField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='password2',
            field=models.IntegerField(blank=True, max_length=150, null=True),
        ),
    ]
