# Generated by Django 3.1.7 on 2021-07-09 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
