# Generated by Django 3.1.7 on 2021-06-29 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0008_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(upload_to='News_image', verbose_name='Sekil'),
        ),
    ]
