# Generated by Django 3.1.7 on 2021-06-29 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0012_category_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'news'},
        ),
    ]
