# Generated by Django 3.1.7 on 2021-07-10 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pese',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('short_description', models.CharField(blank=True, max_length=150, null=True)),
                ('slug', models.SlugField(max_length=150, verbose_name='Slug')),
                ('image', models.ImageField(upload_to='Blog_image', verbose_name='Sekil')),
                ('pese', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.pese')),
            ],
        ),
    ]
